### ISSUE TITLE
Bump co-log-core dependency to >= 0.3

### ISSUE THREAD

**Issue by jonathangenlambda** [qnikst/co-log-concurrent#2]
When using the newest version of co-log from https://github.com/co-log/co-log (the version on Hackage is not the newest one: https://hackage.haskell.org/package/co-log), it has co-log-concurrent removed. However, adding co-log-concurrent to the same project which uses the version of co-log from above causes dependency issues due to different co-log-core versions. 

We have cloned the co-log-concurrent repo and simply bumped the co-log-core dependency to ``co-log-core ^>= 0.3`` as well as stack resolver to ``resolver: lts-18.19`` which required us to bring in ``- co-log-core-0.3.1.0@sha256:9794bdedd1391decd0e22bdfe2b11abcb42e6cff7a4531e1f8882890828f4e63,3816`` as extra-deps, but this solves the issue of incompatible dependencies.

We will create a fork where we bump the dependency as well as the stack resolver and create a PR for this issue.

**Comment by qnikst** [comment]
Resolved, thanks!

Also updated a revision on hackage.
